version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    depends_on:
      - server
    ports:
      - 8080:80
    networks:
      - app_network
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
